# STAGE 1: Build app
# Step 1: Pull node offical image
FROM node:16.13.2-alpine as builder
# Step 2: Define working dir for builder container
WORKDIR /usr/src/app
# Step 3: Copy package.json and package-lock.json files
COPY package*.json ./
# Step 4: Install dependancy 
RUN npm install --legacy-peer-deps
# Step 5: Copy all source code
# Copy the source code to the /app directory
COPY . .

# Build the application
RUN npm run build --  --output-path=dist --configuration=production --output-hashing=all
# STAGE 2: Setup Server
# Step 7: Pull nginx image
FROM nginx:latest
# Step 8: Copy default nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# Step 9: Copy builded application source code
COPY --from=build /usr/src/app/dist/architectui-angular-free /usr/share/nginx/html
# step 10: Expose container port 80
EXPOSE 80
# Step 11: Switch nginx deamon off
# Note: If your container serve multiple service than don't daemon off. 
CMD nginx -g "daemon off;"